nautobot/extras/urls.py
from django.urls import path
from django.views.generic import RedirectView

from nautobot.extras import views
from nautobot.extras.models import (
    ComputedField,
    ConfigContext,
    ConfigContextSchema,
    CustomField,
    CustomLink,
    DynamicGroup,
    ExportTemplate,
    GitRepository,
    GraphQLQuery,
    Job,
    Note,
    JobHook,
    Relationship,
    Secret,
    SecretsGroup,
    Status,
    Tag,
    Webhook,
)


app_name = "extras"
urlpatterns = [
    # Change logging
    path("changelog/", views.ObjectChangeListView.as_view(), name="objectchange_list"),
    path("changelog/<uuid:pk>/", views.ObjectChangeView.as_view(), name="objectchange"),
    # Computed Fields
    path("computed-fields/", views.ComputedFieldListView.as_view(), name="computedfield_list"),
    path("computed-fields/add/", views.ComputedFieldEditView.as_view(), name="computedfield_add"),
    path(
        "computed-fields/delete/",
        views.ComputedFieldBulkDeleteView.as_view(),
        name="computedfield_bulk_delete",
    ),
    path("computed-fields/<slug:slug>/", views.ComputedFieldView.as_view(), name="computedfield"),
    path(
        "computed-fields/<slug:slug>/edit/",
        views.ComputedFieldEditView.as_view(),
        name="computedfield_edit",
    ),
    path(
        "computed-fields/<slug:slug>/delete/",
        views.ComputedFieldDeleteView.as_view(),
        name="computedfield_delete",
    ),
    path(
        "computed-fields/<slug:slug>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="computedfield_changelog",
        kwargs={"model": ComputedField},
    ),
    path(
        "computed-fields/<slug:slug>/notes/",
        views.ObjectNotesView.as_view(),
        name="computedfield_notes",
        kwargs={"model": ComputedField},
    ),
    # Config contexts
    path(
        "config-contexts/",
        views.ConfigContextListView.as_view(),
        name="configcontext_list",
    ),
    path(
        "config-contexts/add/",
        views.ConfigContextEditView.as_view(),
        name="configcontext_add",
    ),
    path(
        "config-contexts/edit/",
        views.ConfigContextBulkEditView.as_view(),
        name="configcontext_bulk_edit",
    ),
    path(
        "config-contexts/delete/",
        views.ConfigContextBulkDeleteView.as_view(),
        name="configcontext_bulk_delete",
    ),
    path(
        "config-contexts/<uuid:pk>/",
        views.ConfigContextView.as_view(),
        name="configcontext",
    ),
    path(
        "config-contexts/<uuid:pk>/edit/",
        views.ConfigContextEditView.as_view(),
        name="configcontext_edit",
    ),
    path(
        "config-contexts/<uuid:pk>/delete/",
        views.ConfigContextDeleteView.as_view(),
        name="configcontext_delete",
    ),
    path(
        "config-contexts/<uuid:pk>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="configcontext_changelog",
        kwargs={"model": ConfigContext},
    ),
    path(
        "config-contexts/<uuid:pk>/notes/",
        views.ObjectNotesView.as_view(),
        name="configcontext_notes",
        kwargs={"model": ConfigContext},
    ),
    # Config context schema
    path(
        "config-context-schemas/",
        views.ConfigContextSchemaListView.as_view(),
        name="configcontextschema_list",
    ),
    path(
        "config-context-schemas/add/",
        views.ConfigContextSchemaEditView.as_view(),
        name="configcontextschema_add",
    ),
    path(
        "config-context-schemas/edit/",
        views.ConfigContextSchemaBulkEditView.as_view(),
        name="configcontextschema_bulk_edit",
    ),
    path(
        "config-context-schemas/delete/",
        views.ConfigContextSchemaBulkDeleteView.as_view(),
        name="configcontextschema_bulk_delete",
    ),
    path(
        "config-context-schemas/<slug:slug>/",
        views.ConfigContextSchemaView.as_view(),
        name="configcontextschema",
    ),
    path(
        "config-context-schemas/<slug:slug>/validation/",
        views.ConfigContextSchemaObjectValidationView.as_view(),
        name="configcontextschema_object_validation",
    ),
    path(
        "config-context-schemas/<slug:slug>/edit/",
        views.ConfigContextSchemaEditView.as_view(),
        name="configcontextschema_edit",
    ),
    path(
        "config-context-schemas/<slug:slug>/delete/",
        views.ConfigContextSchemaDeleteView.as_view(),
        name="configcontextschema_delete",
    ),
    path(
        "config-context-schemas/<slug:slug>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="configcontextschema_changelog",
        kwargs={"model": ConfigContextSchema},
    ),
    path(
        "config-context-schemas/<slug:slug>/notes/",
        views.ObjectNotesView.as_view(),
        name="configcontextschema_notes",
        kwargs={"model": ConfigContextSchema},
    ),
    # Custom fields
    path("custom-fields/", views.CustomFieldListView.as_view(), name="customfield_list"),
    path("custom-fields/add/", views.CustomFieldEditView.as_view(), name="customfield_add"),
    path(
        "custom-fields/delete/",
        views.CustomFieldBulkDeleteView.as_view(),
        name="customfield_bulk_delete",
    ),
    path("custom-fields/<slug:slug>/", views.CustomFieldView.as_view(), name="customfield"),
    path(
        "custom-fields/<slug:slug>/edit/",
        views.CustomFieldEditView.as_view(),
        name="customfield_edit",
    ),
    path(
        "custom-fields/<slug:slug>/delete/",
        views.CustomFieldDeleteView.as_view(),
        name="customfield_delete",
    ),
    path(
        "custom-fields/<slug:slug>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="customfield_changelog",
        kwargs={"model": CustomField},
    ),
    path(
        "custom-fields/<str:name>/notes/",
        views.ObjectNotesView.as_view(),
        name="customfield_notes",
        kwargs={"model": CustomField},
    ),
    # Custom links
    path("custom-links/", views.CustomLinkListView.as_view(), name="customlink_list"),
    path("custom-links/add/", views.CustomLinkEditView.as_view(), name="customlink_add"),
    path(
        "custom-links/delete/",
        views.CustomLinkBulkDeleteView.as_view(),
        name="customlink_bulk_delete",
    ),
    path("custom-links/<uuid:pk>/", views.CustomLinkView.as_view(), name="customlink"),
    path(
        "custom-links/<uuid:pk>/edit/",
        views.CustomLinkEditView.as_view(),
        name="customlink_edit",
    ),
    path(
        "custom-links/<uuid:pk>/delete/",
        views.CustomLinkDeleteView.as_view(),
        name="customlink_delete",
    ),
    path(
        "custom-links/<uuid:pk>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="customlink_changelog",
        kwargs={"model": CustomLink},
    ),
    path(
        "custom-links/<uuid:pk>/notes/",
        views.ObjectNotesView.as_view(),
        name="customlink_notes",
        kwargs={"model": CustomLink},
    ),
    # Dynamic Groups
    path("dynamic-groups/", views.DynamicGroupListView.as_view(), name="dynamicgroup_list"),
    path("dynamic-groups/add/", views.DynamicGroupEditView.as_view(), name="dynamicgroup_add"),
    path(
        "dynamic-groups/delete/",
        views.DynamicGroupBulkDeleteView.as_view(),
        name="dynamicgroup_bulk_delete",
    ),
    path("dynamic-groups/<str:slug>/", views.DynamicGroupView.as_view(), name="dynamicgroup"),
    path("dynamic-groups/<str:slug>/edit/", views.DynamicGroupEditView.as_view(), name="dynamicgroup_edit"),
    path("dynamic-groups/<str:slug>/delete/", views.DynamicGroupDeleteView.as_view(), name="dynamicgroup_delete"),
    path(
        "dynamic-groups/<str:slug>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="dynamicgroup_changelog",
        kwargs={"model": DynamicGroup},
    ),
    path(
        "dynamic-groups/<str:slug>/notes/",
        views.ObjectNotesView.as_view(),
        name="dynamicgroup_notes",
        kwargs={"model": DynamicGroup},
    ),
    # Export Templates
    path(
        "export-templates/",
        views.ExportTemplateListView.as_view(),
        name="exporttemplate_list",
    ),
    path(
        "export-templates/add/",
        views.ExportTemplateEditView.as_view(),
        name="exporttemplate_add",
    ),
    path(
        "export-templates/delete/",
        views.ExportTemplateBulkDeleteView.as_view(),
        name="exporttemplate_bulk_delete",
    ),
    path(
        "export-templates/<uuid:pk>/",
        views.ExportTemplateView.as_view(),
        name="exporttemplate",
    ),
    path(
        "export-templates/<uuid:pk>/edit/",
        views.ExportTemplateEditView.as_view(),
        name="exporttemplate_edit",
    ),
    path(
        "export-templates/<uuid:pk>/delete/",
        views.ExportTemplateDeleteView.as_view(),
        name="exporttemplate_delete",
    ),
    path(
        "export-templates/<uuid:pk>/changelog/",
        views.ObjectChangeLogView.as_view(),
        name="exporttemplate_changelog",
        kwargs={"model": ExportTemplate},
    ),
    path(
        "export-templates/<uuid:pk>/notes/",
        views.ObjectNotesView.as_view(),
        name="exporttemplate_notes",
        kwargs={"model": ExportTemplate},
    ),
    # Git repositories
    path(
        "git-repositories/",
        views.GitRepositoryListView.as_view(),
        name="gitrepository_list",
    ),
    path(
        "git-repositories/add/",
        views.GitRepositoryEditView.as_view(),
        name="gitrepository_add",
    ),
    path(
        "git-repositories/delete/",
        views.GitRepositoryBulkDeleteView.as_view(),
        name="gitrepository_bulk_delete",
    ),
    path(
        "git-repositories/edit/",
        views.GitRepositoryBulkEditView.as_view(),
        name="gitrepository_bulk_edit",
    ),
    path(
        "git-repositories/import/",
        views.GitRepositoryBulkImportView.as_view(),

nautobot/extras/models/secrets.py
import logging

from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.urls import reverse

from jinja2.exceptions import UndefinedError, TemplateSyntaxError

from nautobot.core.fields import AutoSlugField
from nautobot.core.models import BaseModel
from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
from nautobot.extras.choices import SecretsGroupAccessTypeChoices, SecretsGroupSecretTypeChoices
from nautobot.extras.registry import registry
from nautobot.extras.secrets.exceptions import SecretError, SecretParametersError, SecretProviderError
from nautobot.extras.utils import extras_features
from nautobot.utilities.utils import render_jinja2


logger = logging.getLogger(__name__)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "graphql",
    "relationships",
    "webhooks",
)
class Secret(PrimaryModel):
    """
    Data model providing access to a "secret" such as a device credential or a systems-integration token.

    Note that this model **does not** STORE the actual secret data, rather it provides ACCESS to the secret for other
    Nautobot models and APIs to make use of as needed and appropriate.
    """

    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from="name")
    description = models.CharField(max_length=200, blank=True)
    provider = models.CharField(max_length=100)
    parameters = models.JSONField(encoder=DjangoJSONEncoder, default=dict)

    csv_headers = [
        "name",
        "slug",
        "description",
        "provider",
        "parameters",
    ]
    clone_fields = [
        "provider",
    ]

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("extras:secret", args=[self.slug])

    def to_csv(self):
        return (
            self.name,
            self.slug,
            self.description,
            self.provider,
            self.parameters,
        )

    def rendered_parameters(self, obj=None):
        """Render self.parameters as a Jinja2 template with the given object as context."""
        try:
            return {key: render_jinja2(value, {"obj": obj}) for key, value in self.parameters.items()}
        except (TemplateSyntaxError, UndefinedError) as exc:
            raise SecretParametersError(self, registry["secrets_providers"].get(self.provider), str(exc)) from exc

    def get_value(self, obj=None):
        """Retrieve the secret value that this Secret is a representation of.

        May raise a SecretError on failure.

        Args:
            obj (object): Object (Django model or similar) that may provide additional context for this secret.
        """
        provider = registry["secrets_providers"].get(self.provider)
        if not provider:
            raise SecretProviderError(self, None, f'No registered provider "{self.provider}" is available')

        try:
            return provider.get_value_for_secret(self, obj=obj)
        except SecretError:
            raise
        except Exception as exc:
            raise SecretError(self, provider, str(exc)) from exc

    def clean(self):
        provider = registry["secrets_providers"].get(self.provider)
        if not provider:
            raise ValidationError({"provider": f'No registered provider "{self.provider}" is available'})

        # Apply any provider-specific validation of the parameters
        form = provider.ParametersForm(self.parameters)
        form.is_valid()
        form.clean()


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "graphql",
    "relationships",
    "webhooks",
)
class SecretsGroup(OrganizationalModel):
    """A group of related Secrets."""

    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from="name", unique=True)
    description = models.CharField(max_length=200, blank=True)
    secrets = models.ManyToManyField(
        to=Secret, related_name="groups", through="extras.SecretsGroupAssociation", blank=True
    )

    csv_headers = ["name", "slug", "description"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("extras:secretsgroup", args=[self.slug])

    def to_csv(self):
        return (self.name, self.slug, self.description)

    def get_secret_value(self, access_type, secret_type, obj=None, **kwargs):
        """Helper method to retrieve a specific secret from this group.

        May raise SecretError and/or Django ObjectDoesNotExist exceptions; it's up to the caller to handle those.
        """
        secret = self.secrets.through.objects.get(group=self, access_type=access_type, secret_type=secret_type).secret
        return secret.get_value(obj=obj, **kwargs)


@extras_features(
    "graphql",
)
class SecretsGroupAssociation(BaseModel):
    """The intermediary model for associating Secret(s) to SecretsGroup(s)."""

    group = models.ForeignKey(SecretsGroup, on_delete=models.CASCADE)
    secret = models.ForeignKey(Secret, on_delete=models.CASCADE)

    access_type = models.CharField(max_length=32, choices=SecretsGroupAccessTypeChoices)
    secret_type = models.CharField(max_length=32, choices=SecretsGroupSecretTypeChoices)

    class Meta:
        unique_together = (
            # Don't allow the same access-type/secret-type combination to be used more than once in the same group
            ("group", "access_type", "secret_type"),
        )
        ordering = ("group", "access_type", "secret_type")

    def __str__(self):
        return f"{self.group}: {self.access_type} {self.secret_type}: {self.secret}"

nautobot/extras/templates/extras/computedfield_edit.html
{% extends 'generic/object_edit.html' %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
    const slugify_prefer_underscores = true; // Computed fields work better in GraphQL (etc.) with underscore-based slugs
</script>
{% endblock javascript %}

nautobot/extras/templates/extras/configcontextschema_edit.html
{% extends 'generic/object_edit.html' %}
{% load form_helpers %}

{% block form %}
    <div class="panel panel-default">
        <div class="panel-heading"><strong>Config Context Schema</strong></div>
        <div class="panel-body">
            {% render_field form.name %}
            {% render_field form.slug %}
            {% render_field form.description %}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading"><strong>Data Schema</strong></div>
        <div class="panel-body">
            {% render_field form.data_schema %}
        </div>
    </div>
    {% include 'inc/extras_features_edit_form_fields.html' %}
{% endblock %}

nautobot/extras/templates/extras/configcontextschema_validation.html
{% extends 'extras/configcontextschema.html' %}

<h1>{% block title %}{{ object }} - Validation{% endblock %}</h1>

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'utilities/obj_table.html' with table=config_context_table table_template='panel_table.html' heading='Config Contexts' %}
            {% include 'utilities/obj_table.html' with table=device_table table_template='panel_table.html' heading='Devices' %}
            {% include 'utilities/obj_table.html' with table=virtual_machine_table table_template='panel_table.html' heading='Virtual Machines' %}
        </div>
    </div>
{% endblock %}

nautobot/extras/templates/extras/customfield.html
{% extends 'generic/object_detail.html' %}
{% load buttons %}
{% load helpers %}


{% block buttons %}
        {% if perms.extras.add_customfield %}
            {% clone_button object %}
        {% endif %}
        {% if perms.extras.change_customfield %}
            {% edit_button object key="slug" %}
        {% endif %}
        {% if perms.extras.delete_customfield %}
            {% delete_button object key="slug" %}
        {% endif %}
{% endblock buttons %}

{% block content_left_page %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Custom Field</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <tr>
                        {% comment %}2.0 TODO: #824 remove name field{% endcomment %}
                        <td>Name</td>
                        <td><span>{{ object.name }}</span></td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td><span>{{ object.type | capfirst }}</span></td>
                    </tr>
                    <tr>
                        <td>Weight</td>
                        <td><span>{{ object.weight }}</span></td>
                    </tr>
                    <tr>
                        <td>Label</td>
                        <td><span>{{ object.label | placeholder }}</span></td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        <td><span>{{ object.description | render_markdown | placeholder }}</span></td>
                    </tr>
                    <tr>
                        <td>Required</td>
                        <td>{{ object.required | render_boolean }}</td>
                    </tr>
                    <tr>
                        <td>Default</td>
                        <td><span>{{ object.default }}</span></td>
                    </tr>
                    <tr>
                        <td>Filter Logic</td>
                        <td><span>{{ object.filter_logic | capfirst }}</span></td>
                    </tr>
                    <tr>
                        <td>Move to Advanced Tab</td>
                        <td><span>{{ object.advanced_ui | render_boolean }}</span></td>
                    </tr>
                </table>
            </div>
            {% if object.choices.exists %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Custom Field Choices</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <thead>
                        <tr>
                            <th>Value</th>
                            <th>Weight</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for choice in object.choices.all %}
                        <tr>
                            <td>{{ choice.value }}</td>
                            <td>{{ choice.weight }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
{% endblock content_left_page %}

{% block content_right_page %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Assignment</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <tr>
                        <td>Content Types</td>
                        <td>
                            <ul>
                                {% for ct in object.content_types.all %}
                                    <li>{{ ct }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Validation Rules</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <tr>
                        <td>Minimum Value</td>
                        <td><span>{{ object.validation_minimum | placeholder }}</span></td>
                    </tr>
                    <tr>
                        <td>Maximum Value Type</td>
                        <td><span>{{ object.validation_maximum | placeholder }}</span></td>
                    </tr>
                    <tr>
                        <td>Validation Regex</td>
                        <td>
                            {% if object.validation_regex %}
                                <code>{{ object.validation_regex | placeholder }}</code>
                            {% else %}
                                <span>{{ object.validation_regex | placeholder }}</span>
                            {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
{% endblock content_right_page %}

nautobot/extras/templates/extras/gitrepository_result.html
{% extends base_template %}
{% load helpers %}
{% load log_levels %}
{% load static %}

{% block title %}{{ block.super }} - Synchronization Status{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'extras/inc/jobresult.html' with result=result log_table=log_table%}
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    {% include 'extras/inc/jobresult_js.html' with result=result %}
    <script src="{% static 'js/tableconfig.js' %}?v{{ settings.VERSION }}"></script>
    <script src="{% static 'js/log_level_filtering.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}

nautobot/extras/templates/extras/object_changelog.html
{% extends base_template %}
{% load helpers %}

{% block title %}{{ block.super }} - Change Log{% endblock %}

{% block content %}
    {% include 'panel_table.html' %}
    {% include 'inc/paginator.html' with paginator=table.paginator page=table.page %}
    <div class="text-muted">
        Change log retention:
        {% if "CHANGELOG_RETENTION"|settings_or_config %}
            {{ "CHANGELOG_RETENTION"|settings_or_config }} days
        {% else %}
            Indefinite
        {% endif %}
    </div>
{% endblock %}

nautobot/extras/templates/extras/objectchange.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block title %}{{ object }}{% endblock %}

{% block header %}
    <div class="row noprint">
        <div class="col-sm-8 col-md-9">
            <ol class="breadcrumb">
                <li><a href="{% url 'extras:objectchange_list' %}">Change Log</a></li>
                {% if object.related_object.get_absolute_url %}
                    <li><a href="{{ object.related_object.get_absolute_url }}changelog/">{{ object.related_object }}</a></li>
                {% elif object.changed_object and object.changed_object.get_absolute_url %}
                    <li><a href="{{ object.changed_object.get_absolute_url }}changelog/">{{ object.changed_object }}</a></li>
                {% elif object.changed_object is not None %}
                    <li>{{ object.changed_object }}</li>
                {% endif %}
                <li>{{ object }}</li>
            </ol>
        </div>
        <div class="col-sm-4 col-md-3">
            <form action="{% url 'extras:objectchange_list' %}" method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search change logs" />
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-primary">
                            <span class="mdi mdi-magnify" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Change</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <tr>
                        <td>Time</td>
                        <td>
                            {{ object.time }}
                        </td>
                    </tr>
                    <tr>
                        <td>User</td>
                        <td>
                            {{ object.user|default:object.user_name }}
                        </td>
                    </tr>
                    <tr>
                        <td>Action</td>
                        <td>
                            {{ object.get_action_display }}
                        </td>
                    </tr>
                    <tr>
                        <td>Object Type</td>
                        <td>
                            {{ object.changed_object_type }}
                        </td>
                    </tr>
                    <tr>
                        <td>Object</td>
                        <td>
                            {% if object.changed_object and object.changed_object.get_absolute_url %}
                                {{ object.changed_object|hyperlinked_object }}
                            {% else %}
                                {{ object.object_repr }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Request ID</td>
                        <td>
                            {{ object.request_id }}
                        </td>
                    </tr>
                    <tr>
                        <td>Change Context</td>
                        <td>
                            {{ object.get_change_context_display }}
                        </td>
                    </tr>
                    <tr>
                        <td>Change Context Detail</td>
                        <td>
                            {{ object.change_context_detail | placeholder }}
                        </td>
                    </tr>
                </table>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Difference</strong>
                    <div class="btn-group btn-group-xs pull-right noprint">
                        <a {% if prev_change %}href="{% url 'extras:objectchange' pk=prev_change.pk %}"{% else %}disabled{% endif %} class="btn btn-default">
                            <span class="mdi mdi-chevron-left" aria-hidden="true"></span> Previous
                        </a>
                        <a {% if next_change %}href="{% url 'extras:objectchange' pk=next_change.pk %}"{% else %}disabled{% endif %} class="btn btn-default">
                            Next <span class="mdi mdi-chevron-right" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    {% if diff_added == diff_removed %}
                        <span class="text-muted" style="margin-left: 10px;">
                            {% if object.action == 'create' %}
                                Object created
                            {% elif object.action == 'delete' %}
                                Object deleted
                            {% else %}
                                No changes
                            {% endif %}
                        </span>
                    {% else %}
                        <pre style="background-color: #ffdce0;">{{ diff_removed|render_json }}</pre>
                        <pre style="background-color: #cdffd8;">{{ diff_added|render_json }}</pre>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Object Data</strong>
                </div>
                <div class="panel-body">
                    <pre>{{ object.object_data|render_json }}</pre>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% include 'panel_table.html' with table=related_changes_table heading='Related Changes' panel_class='default' %}
            {% if related_changes_count > related_changes_table.rows|length %}
                <div class="pull-right">
                    <a href="{% url 'extras:objectchange_list' %}?request_id={{ object.request_id }}" class="btn btn-primary">See all {{ related_changes_count|add:"1" }} changes</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

nautobot/extras/templates/extras/objectchange_list.html
{% extends 'generic/object_list.html' %}
{% load helpers %}

{% block title %}Change Log{% endblock %}

{% block sidebar %}
    <div class="text-muted">
        Change log retention:
        {% if "CHANGELOG_RETENTION"|settings_or_config %}
            {{ "CHANGELOG_RETENTION"|settings_or_config }} days
        {% else %}
            Indefinite
        {% endif %}
    </div>
{% endblock %}

nautobot/extras/templates/extras/tag_edit.html
{% extends 'generic/object_edit.html' %}
{% load form_helpers %}

{% block form %}
    <div class="panel panel-default">
        <div class="panel-heading"><strong>Tag</strong></div>
        <div class="panel-body">
            {% render_field form.name %}
            {% render_field form.slug %}
            {% render_field form.color %}
            {% render_field form.description %}
            {% render_field form.content_types %}
        </div>
    </div>
    {% include 'inc/extras_features_edit_form_fields.html' %}
{% endblock %}