nautobot/dcim/urls.py
from django.urls import path

from nautobot.extras.views import ObjectChangeLogView, ObjectDynamicGroupsView, ObjectNotesView, ImageAttachmentEditView
from nautobot.ipam.views import ServiceEditView
from . import views
from .models import (
    Cable,
    ConsolePort,
    ConsoleServerPort,
    Device,
    DeviceBay,
    DeviceRole,
    DeviceType,
    FrontPort,
    Interface,
    InventoryItem,
    Location,
    LocationType,
    Manufacturer,
    Platform,
    PowerFeed,
    PowerPanel,
    PowerPort,
    PowerOutlet,
    Rack,
    RackGroup,
    RackReservation,
    RackRole,
    RearPort,
    Region,
    Site,
    VirtualChassis,
)

app_name = "dcim"
urlpatterns = [
    # Regions
    path("regions/", views.RegionListView.as_view(), name="region_list"),
    path("regions/add/", views.RegionEditView.as_view(), name="region_add"),
    path("regions/import/", views.RegionBulkImportView.as_view(), name="region_import"),
    path(
        "regions/delete/",
        views.RegionBulkDeleteView.as_view(),
        name="region_bulk_delete",
    ),
    path("regions/<uuid:pk>/", views.RegionView.as_view(), name="region"),
    path("regions/<uuid:pk>/edit/", views.RegionEditView.as_view(), name="region_edit"),
    path(
        "regions/<uuid:pk>/delete/",
        views.RegionDeleteView.as_view(),
        name="region_delete",
    ),
    path(
        "regions/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="region_changelog",
        kwargs={"model": Region},
    ),
    path(
        "regions/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="region_notes",
        kwargs={"model": Region},
    ),
    # Sites
    path("sites/", views.SiteListView.as_view(), name="site_list"),
    path("sites/add/", views.SiteEditView.as_view(), name="site_add"),
    path("sites/import/", views.SiteBulkImportView.as_view(), name="site_import"),
    path("sites/edit/", views.SiteBulkEditView.as_view(), name="site_bulk_edit"),
    path("sites/delete/", views.SiteBulkDeleteView.as_view(), name="site_bulk_delete"),
    path("sites/<slug:slug>/", views.SiteView.as_view(), name="site"),
    path("sites/<slug:slug>/edit/", views.SiteEditView.as_view(), name="site_edit"),
    path("sites/<slug:slug>/delete/", views.SiteDeleteView.as_view(), name="site_delete"),
    path(
        "sites/<slug:slug>/changelog/",
        ObjectChangeLogView.as_view(),
        name="site_changelog",
        kwargs={"model": Site},
    ),
    path(
        "sites/<slug:slug>/notes/",
        ObjectNotesView.as_view(),
        name="site_notes",
        kwargs={"model": Site},
    ),
    path(
        "sites/<uuid:object_id>/images/add/",
        ImageAttachmentEditView.as_view(),
        name="site_add_image",
        kwargs={"model": Site},
    ),
    # Location types
    path("location-types/", views.LocationTypeListView.as_view(), name="locationtype_list"),
    path("location-types/add/", views.LocationTypeEditView.as_view(), name="locationtype_add"),
    path("location-types/import/", views.LocationTypeBulkImportView.as_view(), name="locationtype_import"),
    path("location-types/delete/", views.LocationTypeBulkDeleteView.as_view(), name="locationtype_bulk_delete"),
    path("location-types/<slug:slug>/", views.LocationTypeView.as_view(), name="locationtype"),
    path("location-types/<slug:slug>/edit/", views.LocationTypeEditView.as_view(), name="locationtype_edit"),
    path("location-types/<slug:slug>/delete/", views.LocationTypeDeleteView.as_view(), name="locationtype_delete"),
    path(
        "location-types/<slug:slug>/changelog/",
        ObjectChangeLogView.as_view(),
        name="locationtype_changelog",
        kwargs={"model": LocationType},
    ),
    path(
        "location-types/<slug:slug>/notes/",
        ObjectNotesView.as_view(),
        name="locationtype_notes",
        kwargs={"model": LocationType},
    ),
    # Locations
    path("locations/", views.LocationListView.as_view(), name="location_list"),
    path("locations/add/", views.LocationEditView.as_view(), name="location_add"),
    path("locations/edit/", views.LocationBulkEditView.as_view(), name="location_bulk_edit"),
    path("locations/import/", views.LocationBulkImportView.as_view(), name="location_import"),
    path("locations/delete/", views.LocationBulkDeleteView.as_view(), name="location_bulk_delete"),
    path("locations/<slug:slug>/", views.LocationView.as_view(), name="location"),
    path("locations/<slug:slug>/edit/", views.LocationEditView.as_view(), name="location_edit"),
    path("locations/<slug:slug>/delete/", views.LocationDeleteView.as_view(), name="location_delete"),
    path(
        "locations/<slug:slug>/changelog/",
        ObjectChangeLogView.as_view(),
        name="location_changelog",
        kwargs={"model": Location},
    ),
    path(
        "locations/<slug:slug>/notes/",
        ObjectNotesView.as_view(),
        name="location_notes",
        kwargs={"model": Location},
    ),
    path(
        "locations/<slug:slug>/images/add/",
        ImageAttachmentEditView.as_view(),
        name="location_add_image",
        kwargs={"model": Location},
    ),
    # Rack groups
    path("rack-groups/", views.RackGroupListView.as_view(), name="rackgroup_list"),
    path("rack-groups/add/", views.RackGroupEditView.as_view(), name="rackgroup_add"),
    path(
        "rack-groups/import/",
        views.RackGroupBulkImportView.as_view(),
        name="rackgroup_import",
    ),
    path(
        "rack-groups/delete/",
        views.RackGroupBulkDeleteView.as_view(),
        name="rackgroup_bulk_delete",
    ),
    path("rack-groups/<uuid:pk>/", views.RackGroupView.as_view(), name="rackgroup"),
    path(
        "rack-groups/<uuid:pk>/edit/",
        views.RackGroupEditView.as_view(),
        name="rackgroup_edit",
    ),
    path(
        "rack-groups/<uuid:pk>/delete/",
        views.RackGroupDeleteView.as_view(),
        name="rackgroup_delete",
    ),
    path(
        "rack-groups/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="rackgroup_changelog",
        kwargs={"model": RackGroup},
    ),
    path(
        "rack-groups/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="rackgroup_notes",
        kwargs={"model": RackGroup},
    ),
    # Rack roles
    path("rack-roles/", views.RackRoleListView.as_view(), name="rackrole_list"),
    path("rack-roles/add/", views.RackRoleEditView.as_view(), name="rackrole_add"),
    path(
        "rack-roles/import/",
        views.RackRoleBulkImportView.as_view(),
        name="rackrole_import",
    ),
    path(
        "rack-roles/delete/",
        views.RackRoleBulkDeleteView.as_view(),
        name="rackrole_bulk_delete",
    ),
    path("rack-roles/<uuid:pk>/", views.RackRoleView.as_view(), name="rackrole"),
    path(
        "rack-roles/<uuid:pk>/edit/",
        views.RackRoleEditView.as_view(),
        name="rackrole_edit",
    ),
    path(
        "rack-roles/<uuid:pk>/delete/",
        views.RackRoleDeleteView.as_view(),
        name="rackrole_delete",
    ),
    path(
        "rack-roles/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="rackrole_changelog",
        kwargs={"model": RackRole},
    ),
    path(
        "rack-roles/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="rackrole_notes",
        kwargs={"model": RackRole},
    ),
    # Rack reservations
    path(
        "rack-reservations/",
        views.RackReservationListView.as_view(),
        name="rackreservation_list",
    ),
    path(
        "rack-reservations/add/",
        views.RackReservationEditView.as_view(),
        name="rackreservation_add",
    ),
    path(
        "rack-reservations/import/",
        views.RackReservationImportView.as_view(),
        name="rackreservation_import",
    ),
    path(
        "rack-reservations/edit/",
        views.RackReservationBulkEditView.as_view(),
        name="rackreservation_bulk_edit",
    ),
    path(
        "rack-reservations/delete/",
        views.RackReservationBulkDeleteView.as_view(),
        name="rackreservation_bulk_delete",
    ),
    path(
        "rack-reservations/<uuid:pk>/",
        views.RackReservationView.as_view(),
        name="rackreservation",
    ),
    path(
        "rack-reservations/<uuid:pk>/edit/",
        views.RackReservationEditView.as_view(),
        name="rackreservation_edit",
    ),
    path(
        "rack-reservations/<uuid:pk>/delete/",
        views.RackReservationDeleteView.as_view(),
        name="rackreservation_delete",
    ),
    path(
        "rack-reservations/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="rackreservation_changelog",
        kwargs={"model": RackReservation},
    ),
    path(
        "rack-reservations/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="rackreservation_notes",
        kwargs={"model": RackReservation},
    ),
    # Racks
    path("racks/", views.RackListView.as_view(), name="rack_list"),
    path(
        "rack-elevations/",
        views.RackElevationListView.as_view(),
        name="rack_elevation_list",
    ),
    path("racks/add/", views.RackEditView.as_view(), name="rack_add"),
    path("racks/import/", views.RackBulkImportView.as_view(), name="rack_import"),
    path("racks/edit/", views.RackBulkEditView.as_view(), name="rack_bulk_edit"),
    path("racks/delete/", views.RackBulkDeleteView.as_view(), name="rack_bulk_delete"),
    path("racks/<uuid:pk>/", views.RackView.as_view(), name="rack"),
    path("racks/<uuid:pk>/edit/", views.RackEditView.as_view(), name="rack_edit"),
    path("racks/<uuid:pk>/delete/", views.RackDeleteView.as_view(), name="rack_delete"),
    path(
        "racks/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="rack_changelog",
        kwargs={"model": Rack},
    ),
    path(
        "racks/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="rack_notes",

nautobot/dcim/models/sites.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import Q
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from timezone_field import TimeZoneField

from nautobot.dcim.fields import ASNField
from nautobot.extras.models import StatusModel
from nautobot.extras.utils import extras_features
from nautobot.core.fields import AutoSlugField
from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
from nautobot.utilities.fields import NaturalOrderingField
from nautobot.utilities.mptt import TreeManager

__all__ = (
    "Region",
    "Site",
)


#
# Regions
#


@extras_features(
    "custom_fields",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "webhooks",
)
class Region(MPTTModel, OrganizationalModel):
    """
    Sites can be grouped within geographic Regions.
    """

    parent = TreeForeignKey(
        to="self",
        on_delete=models.CASCADE,
        related_name="children",
        blank=True,
        null=True,
        db_index=True,
    )
    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from="name")
    description = models.CharField(max_length=200, blank=True)

    objects = TreeManager()

    csv_headers = ["name", "slug", "parent", "description"]

    class MPTTMeta:
        order_insertion_by = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dcim:region", args=[self.pk])

    def to_csv(self):
        return (
            self.name,
            self.slug,
            self.parent.name if self.parent else None,
            self.description,
        )

    def get_site_count(self):
        return Site.objects.filter(Q(region=self) | Q(region__in=self.get_descendants())).count()

    def to_objectchange(self, action, object_data_exclude=None, **kwargs):
        if object_data_exclude is None:
            object_data_exclude = []
        # Remove MPTT-internal fields
        object_data_exclude += ["level", "lft", "rght", "tree_id"]
        return super().to_objectchange(action, object_data_exclude=object_data_exclude, **kwargs)


#
# Sites
#


@extras_features(
    "custom_fields",
    "custom_links",
    "export_templates",
    "custom_validators",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class Site(PrimaryModel, StatusModel):
    """
    A Site represents a geographic location within a network; typically a building or campus. The optional facility
    field can be used to include an external designation, such as a data center name (e.g. Equinix SV6).
    """

    name = models.CharField(max_length=100, unique=True)
    _name = NaturalOrderingField(target_field="name", max_length=100, blank=True, db_index=True)
    slug = AutoSlugField(populate_from="name")
    region = models.ForeignKey(
        to="dcim.Region",
        on_delete=models.SET_NULL,
        related_name="sites",
        blank=True,
        null=True,
    )
    tenant = models.ForeignKey(
        to="tenancy.Tenant",
        on_delete=models.PROTECT,
        related_name="sites",
        blank=True,
        null=True,
    )
    facility = models.CharField(max_length=50, blank=True, help_text="Local facility ID or description")
    asn = ASNField(
        blank=True,
        null=True,
        verbose_name="ASN",
        help_text="32-bit autonomous system number",
    )
    time_zone = TimeZoneField(blank=True)
    description = models.CharField(max_length=200, blank=True)
    physical_address = models.CharField(max_length=200, blank=True)
    shipping_address = models.CharField(max_length=200, blank=True)
    latitude = models.DecimalField(
        max_digits=8,
        decimal_places=6,
        blank=True,
        null=True,
        help_text="GPS coordinate (latitude)",
    )
    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        blank=True,
        null=True,
        help_text="GPS coordinate (longitude)",
    )
    contact_name = models.CharField(max_length=50, blank=True)
    contact_phone = models.CharField(max_length=20, blank=True)
    contact_email = models.EmailField(blank=True, verbose_name="Contact E-mail")
    comments = models.TextField(blank=True)
    images = GenericRelation(to="extras.ImageAttachment")

    csv_headers = [
        "name",
        "slug",
        "status",
        "region",
        "tenant",
        "facility",
        "asn",
        "time_zone",
        "description",
        "physical_address",
        "shipping_address",
        "latitude",
        "longitude",
        "contact_name",
        "contact_phone",
        "contact_email",
        "comments",
    ]
    clone_fields = [
        "status",
        "region",
        "tenant",
        "facility",
        "asn",
        "time_zone",
        "description",
        "physical_address",
        "shipping_address",
        "latitude",
        "longitude",
        "contact_name",
        "contact_phone",
        "contact_email",
    ]

    class Meta:
        ordering = ("_name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dcim:site", args=[self.slug])

    def to_csv(self):
        return (
            self.name,
            self.slug,
            self.get_status_display(),
            self.region.name if self.region else None,
            self.tenant.name if self.tenant else None,
            self.facility,
            self.asn,
            self.time_zone,
            self.description,
            self.physical_address,
            self.shipping_address,
            self.latitude,
            self.longitude,
            self.contact_name,
            self.contact_phone,
            self.contact_email,
            self.comments,
        )

nautobot/dcim/templates/dcim/cable_edit.html
{% extends 'generic/object_edit.html' %}

{% block form %}
    {% include 'dcim/inc/cable_form.html' %}
{% endblock %}

nautobot/dcim/templates/dcim/connections_list.html
{% extends 'base.html' %}
{% load buttons %}

{% block content %}
<div class="pull-right noprint">
    {% export_button content_type %}
</div>
<h1>{% block title %}{{ title }}{% endblock %}</h1>
<div class="row">
	  <div class="col-md-12">
        <div class="col-md-3 pull-right right-side-panel noprint">
            {% include 'inc/search_panel.html' %}
        </div>
        {% include 'responsive_table.html' %}
        {% include 'inc/paginator.html' with paginator=table.paginator page=table.page %}
    </div>
</div>
{% endblock %}

nautobot/dcim/templates/dcim/consoleport.html
{% extends 'dcim/device_component.html' %}
{% load helpers %}

{% block content_left_page %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Console Port</strong>
                </div>
                <table class="table table-hover panel-body attr-table">
                    <tr>
                        <td>Device</td>
                        <td>{{ object.device|hyperlinked_object }}</td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>Label</td>
                        <td>{{ object.label|placeholder }}</td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td>{{ object.get_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        <td>{{ object.description|placeholder }}</td>
                    </tr>
                </table>
            </div>
{% endblock content_left_page %}

{% block content_right_page %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Connection</strong>
                </div>
                {% if object.cable %}
                    <table class="table table-hover panel-body attr-table">
                        <tr>
                            <td>Cable</td>
                            <td>
                                {{ object.cable|hyperlinked_object }}
                                <a href="{% url 'dcim:consoleport_trace' pk=object.pk %}" class="btn btn-primary btn-xs" title="Trace">
                                    <i class="mdi mdi-transit-connection-variant" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                        {% if object.connected_endpoint %}
                            <tr>
                                <td>Device</td>
                                <td>{{ object.connected_endpoint.device|hyperlinked_object }}</td>
                            </tr>
                            <tr>
                                <td>Console Server Port</td>
                                <td>{{ object.connected_endpoint|hyperlinked_object }}</td>
                            </tr>
                            <tr>
                                <td>Type</td>
                                <td>{{ object.connected_endpoint.get_type_display|placeholder }}</td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td>{{ object.connected_endpoint.description|placeholder }}</td>
                            </tr>
                            <tr>
                                <td>Path Status</td>
                                <td>
                                    {% if object.path.is_active %}
                                        <span class="label label-success">Reachable</span>
                                    {% else %}
                                        <span class="label label-danger">Not Reachable</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    </table>
                {% else %}
                    <div class="panel-body text-muted">
                        Not connected
                        {% if perms.dcim.add_cable %}
                            <span class="dropdown pull-right">
                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="mdi mdi-ethernet-cable" aria-hidden="true"></span> Connect
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{% url 'dcim:consoleport_connect' termination_a_id=object.pk termination_b_type='console-server-port' %}?return_url={{ object.get_absolute_url }}">Console Server Port</a></li>
                                    <li><a href="{% url 'dcim:consoleport_connect' termination_a_id=object.pk termination_b_type='front-port' %}?return_url={{ object.get_absolute_url }}">Front Port</a></li>
                                    <li><a href="{% url 'dcim:consoleport_connect' termination_a_id=object.pk termination_b_type='rear-port' %}?return_url={{ object.get_absolute_url }}">Rear Port</a></li>
                                </ul>
                            </span>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
{% endblock content_right_page %}

nautobot/dcim/templates/dcim/device_component_add.html
{% extends 'base.html' %}
{% load form_helpers %}

{% block title %}Create {{ component_type }}{% endblock %}

{% block content %}
<form action="" method="post" class="form form-horizontal">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% if form.non_field_errors %}
                <div class="panel panel-danger">
                    <div class="panel-heading"><strong>Errors</strong></div>
                    <div class="panel-body">
                        {{ form.non_field_errors }}
                    </div>
                </div>
            {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>{{ component_type|title }}</strong>
                </div>
                <div class="panel-body">
                    {% render_form form %}
                </div>
            </div>
            {% include 'inc/extras_features_edit_form_fields.html' with form=model_form %}
            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" name="_create" class="btn btn-primary">Create</button>
                    <button type="submit" name="_addanother" class="btn btn-primary">Create and Add More</button>
                    <a href="{{ return_url }}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

nautobot/dcim/templates/dcim/device_import_child.html
{% extends 'generic/object_bulk_import.html' %}

{% block tabs %}
    {% include 'dcim/inc/device_import_header.html' with active_tab='child_import' %}
{% endblock %}

nautobot/dcim/templates/dcim/interface_bulk_delete.html
{% extends 'generic/object_bulk_delete.html' %}

{% block message_extra %}This would also delete any/all child interfaces of these interfaces.{% endblock %}

nautobot/dcim/templates/dcim/powerpanel.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block extra_breadcrumbs %}
                <li>{{ object.site|hyperlinked_object }}</li>
                {% if object.rack_group %}
                    <li>{{ object.rack_group|hyperlinked_object }}</li>
                {% endif %}
{% endblock extra_breadcrumbs %}

{% block content_left_page %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Power Panel</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                <tr>
                    <td>Site</td>
                    <td>{{ object.site|hyperlinked_object }}</td>
                </tr>
                <tr>
                    <td>Location</td>
                    <td>{% include 'dcim/inc/location_hierarchy.html' with location=object.location %}</td>
                </tr>
                <tr>
                    <td>Rack Group</td>
                    <td>{{ object.rack_group|hyperlinked_object }}</td>
                </tr>
            </table>
        </div>
{% endblock content_left_page %}

{% block content_full_width_page %}
        {% include 'panel_table.html' with table=powerfeed_table heading='Connected Feeds' %}
{% endblock content_full_width_page %}

nautobot/dcim/templates/dcim/rack_elevation_list.html
{% extends 'base.html' %}
{% load helpers %}
{% load static %}

{% block content %}
<div class="btn-toolbar pull-right noprint" role="toolbar">
    <button class="btn btn-default toggle-images" selected="selected">
        <span class="mdi mdi mdi-checkbox-marked-circle-outline" aria-hidden="true"></span> Show Images
    </button>
    <div class="btn-group" role="group">
        <a href="{% url 'dcim:rack_elevation_list' %}{% querystring request face='front' %}" class="btn btn-default{% if rack_face == 'front' %} active{% endif %}">Front</a>
        <a href="{% url 'dcim:rack_elevation_list' %}{% querystring request face='rear' %}" class="btn btn-default{% if rack_face == 'rear' %} active{% endif %}">Rear</a>
    </div>
    <div class="btn-group" role="group">
        <a href="{% url 'dcim:rack_elevation_list' %}{% querystring request reverse=None %}" class="btn btn-default{% if not reverse %} active{% endif %}">Normal</a>
        <a href="{% url 'dcim:rack_elevation_list' %}{% querystring request reverse='true' %}" class="btn btn-default{% if reverse %} active{% endif %}">Reversed</a>
    </div>
</div>
<h1>{% block title %}Rack Elevations{% endblock %}</h1>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-3 pull-right right-side-panel noprint">
            {% include 'inc/search_panel.html' %}
        </div>
        {% if page %}
            <div style="white-space: nowrap; overflow-x: scroll;">
                {% for rack in page %}
                    <div style="display: inline-block; margin-right: 12px; width: 254px">
                      <div style="margin-left: 30px">
                        <div class="text-center">
                            <strong>{{ rack|hyperlinked_object }}</strong>
                            {% if rack.role %}
                                <br /><small class="label" style="color: {{ rack.role.color|fgcolor }}; background-color: #{{ rack.role.color }}">{{ rack.role }}</small>
                            {% endif %}
                            {% if rack.facility_id %}
                                <br /><small class="text-muted">{{ rack.facility_id }}</small>
                            {% endif %}
                        </div>
                        {% include 'dcim/inc/rack_elevation.html' with object=rack face=rack_face %}
                        <div class="clearfix"></div>
                        <div class="text-center">
                            <strong>{{ rack|hyperlinked_object }}</strong>
                            {% if rack.facility_id %}
                                <small class="text-muted">({{ rack.facility_id }})</small>
                            {% endif %}
                        </div>
                      </div>
                    </div>
                {% endfor %}
            </div>
            <br />
            {% include 'inc/paginator.html' %}
        {% else %}
            <p>No racks found</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'js/rack_elevations.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}

nautobot/dcim/templates/dcim/rackreservation.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}
{% load static %}

{% block extra_breadcrumbs %}
                <li>{{ object.rack|hyperlinked_object }}</li>
{% endblock extra_breadcrumbs %}

{% block content_left_page %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Rack</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                {% with rack=object.rack %}
                    <tr>
                        <td>Site</td>
                        <td>
                            {% if rack.site.region %}
                                {{ rack.site.region|hyperlinked_object }} /
                            {% endif %}
                            {{ rack.site|hyperlinked_object }}
                        </td>
                    </tr>
                    <tr>
                        <td>Group</td>
                        <td>
                            {% if rack.group %}
                                <a href="{% url 'dcim:rack_list' %}?site={{ rack.site.slug }}&group={{ rack.group.slug }}">{{ rack.group }}</a>
                            {% else %}
                                <span class="text-muted">None</span>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Rack</td>
                        <td>{{ rack|hyperlinked_object }}</td>
                    </tr>
                {% endwith %}
            </table>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Reservation Details</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                <tr>
                    <td>Units</td>
                    <td>{{ object.unit_list }}</td>
                </tr>
                <tr>
                    <td>Tenant</td>
                    <td>
                        {% if object.tenant and object.tenant.group %}
                            {{ object.tenant.group|hyperlinked_object }} /
                        {% endif %}
                        {{ object.tenant|hyperlinked_object }}
                    </td>
                </tr>
                <tr>
                    <td>User</td>
                    <td>{{ object.user }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ object.description }}</td>
                </tr>
            </table>
        </div>
{% endblock content_left_page %}

{% block content_right_page %}
        <div class="row" style="margin-bottom: 20px">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="rack_header">
                    <h4>Front</h4>
                </div>
                {% include 'dcim/inc/rack_elevation.html' with object=object.rack face='front' %}
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="rack_header">
                    <h4>Rear</h4>
                </div>
                {% include 'dcim/inc/rack_elevation.html' with object=object.rack face='rear' %}
            </div>
        </div>
{% endblock content_right_page %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/rack_elevations.js' %}?v{{ settings.VERSION }}"></script>
{% endblock javascript %}